
FROM node:14.5-alpine3.12 as builder

LABEL version="1.0"
LABEL description="Alpha plus admin"

WORKDIR /app/client/alpha-p-admin

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
EXPOSE 3001
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/client/alpha-p-admin/build /usr/share/admin/nginx/html