
FROM node:14.5-alpine3.12 as builder

LABEL version="1.0"
LABEL description="Alpha plus web app"

WORKDIR /app/client/alpha-p-web

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/client/alpha-p-web/build /usr/share/nginx/html
EXPOSE 3000
CMD ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && nginx -g "daemon off;"